export const SAGA_INCREMENT = 'SAGA_INCREMENT';
export const SAGA_DECREMENT = 'SAGA_DECREMENT';
export const SAGA_INCREMENT_ASYNC = 'SAGA_INCREMENT_ASYNC';
export const SAGA_DECREMENT_ASYNC = 'SAGA_DECREMENT_ASYNC';
